### PR TITLE
Add WORKING_DIRECTORY variable

### PR DESCRIPTION
**Pull request by cedrickring**
Add a WORKING_DIRECTORY variable to specify the directory where the release asset is located.

### CODE REVIEW

**Comment by JasonEtco** [comment]
Thanks for the PR! I'm not sure that this is necessary, as you can specify the full path in the `args` anyway:

```workflow
action "upload" {
  uses = "JasonEtco/upload-to-release@master"
  args = "path/to/my/file.zip
}
```

Does that sound right, or am I missing something?

**Comment by cedrickring** [comment]
Oh yes youre right. I probably did something wrong in the first place, thought it was the wrong workdir. Though the file name is wrong when specified as `path/to/my/file` (see [here](https://github.com/cedrickring/test/releases), should be `test.txt` not `dir.test.txt`).

Maybe removing the directory part from the path should work?

**Comment by JasonEtco** [comment]
Seems right @cedrickring! You can try this too:

```
args = "./dir/test.txt application/octet-stream"
```

The file name is interesting though - this Action names the file being uploaded according to the full path, and I guess GitHub transforms the `/` characters to a `.`. Definitely a bug; it should just take the file name, not the full path, as the `name=""` query param:

https://github.com/JasonEtco/upload-to-release/blob/22eb494e15702e0787929819812959aa8a10caaf/upload-to-release#L37

If you're interested in a PR for that, that'd be super helpful!

**Comment by JasonEtco** [comment]
This looks like a good start:

```bash
❯ basename "path/example.txt"
example.txt
```

**Comment by JasonEtco** [comment]
I've gone ahead and implemented that fix over in #4. I'm going to close this PR since I think its no longer needed. Thanks a lot for pointing out this bug ❤️

**Comment by cedrickring** [comment]
Thanks for fixing this! 👍

**Pull request closed without merging**
